packages:
  - "."

minimumReleaseAgeExclude:
  - bulk-sms-bd
  - nhb-toolbox
  - nhb-hooks

minimumReleaseAge: 120

allowBuilds:
  esbuild: true
  sharp: false

overrides:
  "nodemailer": "^8.0.0"

peerDependencyRules:
  allowedVersions:
    "nodemailer": "^8.0.0"
